# Generated by Django 6.0.2 on 2026-03-06 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('description', models.TextField(verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Prix (FCFA)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse de livraison')),
                ('zone', models.CharField(choices=[('almadies', 'Almadies'), ('kounoune', 'Kounoune'), ('autre', 'Autre zone Dakar')], max_length=20, verbose_name='Zone')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('message', models.TextField(blank=True, verbose_name='Message / Remarques')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
    ]
